### PR TITLE
make everything const

### PR DESCRIPTION
**Pull request by TheBotlyNoob**

### CODE REVIEW

**Comment by TheBotlyNoob** [comment]
I don't think we can make it const without raising the MSRV because I'm getting 
```rust
error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
   --> src\lib.rs:311:6
    |
311 | impl<T, S> Keyboard<T, S>
    |      ^
    |
    = note: for more information, see issue https://github.com/rust-lang/rust/issues/57563
    = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

**Comment by thejpster** [comment]
Yes you'll need to raise the MSRV to 1.56 for this to work. I'm fine with that.

**Comment by TheBotlyNoob** [comment]
:+1:

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
thank you!

**Pull request merged**
